version: '3.8'

services:
  backend-python:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=clinical_trials
      - DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data: 